import type { DashboardCardConfig, DashboardCardId } from '@/lib/types/dashboard';

export const CARD_REGISTRY: Record<DashboardCardId, DashboardCardConfig> = {
  balance: {
    id: 'balance',
    title: 'Account Balance',
    icon: 'CreditCard',
    minW: 3,
    minH: 2,
    defaultW: 6,
    defaultH: 3,
  },
  announcements: {
    id: 'announcements',
    title: 'Announcements',
    icon: 'Megaphone',
    minW: 3,
    minH: 2,
    defaultW: 6,
    defaultH: 3,
  },
  maintenance: {
    id: 'maintenance',
    title: 'Maintenance Requests',
    icon: 'Wrench',
    minW: 3,
    minH: 2,
    defaultW: 6,
    defaultH: 3,
  },
  payments: {
    id: 'payments',
    title: 'Recent Payments',
    icon: 'Receipt',
    minW: 3,
    minH: 2,
    defaultW: 6,
    defaultH: 3,
  },
  events: {
    id: 'events',
    title: 'Upcoming Events',
    icon: 'Calendar',
    minW: 3,
    minH: 2,
    defaultW: 6,
    defaultH: 3,
  },
  household: {
    id: 'household',
    title: 'Household Members',
    icon: 'Users',
    minW: 3,
    minH: 2,
    defaultW: 6,
    defaultH: 2,
  },
  documents: {
    id: 'documents',
    title: 'Documents',
    icon: 'FileText',
    minW: 3,
    minH: 2,
    defaultW: 6,
    defaultH: 3,
  },
  amenities: {
    id: 'amenities',
    title: 'Amenities',
    icon: 'Building2',
    minW: 3,
    minH: 2,
    defaultW: 6,
    defaultH: 3,
  },
};
