import type { DashboardCardConfig, DashboardCardId } from '@/lib/types/dashboard';

/**
 * Card sizes calibrated for rowHeight=30, margin=18.
 * Formula: pixelHeight = h * 30 + (h - 1) * 18
 * h=5 → 222px, h=6 → 270px, h=7 → 318px, h=8 → 366px
 */
export const CARD_REGISTRY: Record<DashboardCardId, DashboardCardConfig> = {
  balance: {
    id: 'balance',
    title: 'Account Balance',
    icon: 'CreditCard',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 5,
  },
  announcements: {
    id: 'announcements',
    title: 'Announcements',
    icon: 'Megaphone',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 7,
  },
  maintenance: {
    id: 'maintenance',
    title: 'Maintenance Requests',
    icon: 'Wrench',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 7,
  },
  payments: {
    id: 'payments',
    title: 'Recent Payments',
    icon: 'Receipt',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 7,
  },
  events: {
    id: 'events',
    title: 'Upcoming Events',
    icon: 'Calendar',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 6,
  },
  household: {
    id: 'household',
    title: 'Household Members',
    icon: 'Users',
    minW: 3,
    minH: 3,
    defaultW: 6,
    defaultH: 5,
  },
  documents: {
    id: 'documents',
    title: 'Documents',
    icon: 'FileText',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 6,
  },
  amenities: {
    id: 'amenities',
    title: 'Amenities',
    icon: 'Building2',
    minW: 3,
    minH: 3,
    defaultW: 6,
    defaultH: 5,
  },
  'amenity-calendar': {
    id: 'amenity-calendar',
    title: 'Amenity Calendar',
    icon: 'CalendarDays',
    minW: 3,
    minH: 7,
    defaultW: 6,
    defaultH: 10,
  },
  voting: {
    id: 'voting',
    title: 'Active Ballots',
    icon: 'Vote',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 5,
  },
  'bulletin-board': {
    id: 'bulletin-board',
    title: 'Bulletin Board',
    icon: 'ClipboardList',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 7,
  },
  violations: {
    id: 'violations',
    title: 'Open Violations',
    icon: 'ShieldAlert',
    minW: 3,
    minH: 3,
    defaultW: 6,
    defaultH: 5,
  },
  vendors: {
    id: 'vendors',
    title: 'Vendors & Businesses',
    icon: 'Store',
    minW: 3,
    minH: 4,
    defaultW: 6,
    defaultH: 6,
  },
};
